mytemplate308/blog/urls.py
from django.urls import path

from . import views

### BLOG URLS ###

app_name = 'blog'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    # path('<int:post_id>/', views.detail, name='detail')
    # path('<int:post_id>/', views.detail_modern, name='detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('edit/<int:post_id>/', views.edit, name='edit'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

mytemplate308/mytemplate308/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import home

urlpatterns = [
    path('', home, name="home"),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

mytemplate308/blog/models.py
from django.db import models

import datetime
from django.utils import timezone

### BLOG MODELS ###

class Post(models.Model):

    title = models.CharField(max_length=255)
    content = models.CharField(max_length=5000)
    # TODO: this field must be datetime field!
    created_at = models.DateField(auto_now=True)
    # TODO: this field must be renamed to updated_at
    published = models.DateField(auto_now_add=True)
    # user = models.ForeignKey('User', on_delete=models.CASCADE())

    def __str__(self):
        return f"Post title:{self.title}"

    def was_published_recently(self):
        # return self.created_at >= timezone.now().date() - datetime.timedelta(days=1)
        # Fixing the bug -> got from testcase! (test_was_published_recently_with_future_post)
        now = timezone.now()
        return now.date() - datetime.timedelta(days=1) <= self.created_at <= now.date()

mytemplate308/blog/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Post

### BLOG VIEWS ###


def index(request):
    lastest_posts = Post.objects.order_by('-created_at')[:5]
    # output = ', '.join([i.title for i in lastest_posts])
    # return HttpResponse(output)
    template = loader.get_template("blog/index.html")
    context = {'lastest_posts': lastest_posts}
    return HttpResponse(template.render(context, request))


class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'lastest_posts'

    def get_queryset(self):
        """Return the last five published questions."""
        return Post.objects.order_by('-created_at')[:5]


def detail(request, post_id):
    try:
        post = Post.objects.get(id=post_id)
    except Post.DoesNotExist:
        raise Http404
    template = loader.get_template("blog/detail.html")
    context = {'post': post}
    return HttpResponse(template.render(context, request))


def detail_modern(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, "blog/detail.html", {'post': post})


class DetailView(generic.DetailView):
    model = Post
    template_name = "blog/detail.html"


def create(request):
    return HttpResponse("create.")


def edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, "blog/edit.html", {'post': post})

def edit_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    try:
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.save()
        return HttpResponseRedirect(reverse('blog:detail', args=(post.id,)))
    except:
        return render(request, 'blog/detail.html', {'post': post, 'error_message': 'some error!'})


def delete(request, post_id):
    return HttpResponse("delete id: %s" % post_id)

mytemplate308/mytemplate308/views.py
from django.http import HttpResponse

def home(request):
    return HttpResponse("Hello, you are home.")

mytemplate308/blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
</head>
<body>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% if post %}
        <h1> <a href="{% url 'blog:edit' post.id %}">{{ post.title }}</a> </h1>
        <span> {{ post.content }} </span>
    {% endif %}

</body>
</html>

mytemplate308/blog/templates/blog/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
</head>
<body>
    <form action="{% url 'blog:edit_post' post.id %}" method="post">
        {% csrf_token %}
        <label for="title"> Title </label>
        <input type="text" name="title" id="{{ post.id }}" value="{{ post.title }}">
        <br>
        <label for="content"> Content </label>
        <input type="text" name="content" value="{{ post.content }}">
        <br>
        <input type="submit" value="Edit">
    </form>
</body>
</html>

mytemplate308/blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
</head>
<body>

    {% if lastest_posts %}
        <ul>
        {% for post in lastest_posts %}
            <!--<li><a href="/blog/{{ post.id }}/">{{ post.title }}</a></li>-->
            <li><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No Blog Post is available.</p>
    {% endif %}

</body>
</html>